### ISSUE TITLE
Support GHC < 8.4

### ISSUE THREAD

**Issue by akshaymankar** [krdlab/haskell-oidc-client#30]
The compilation fails with this error:

```
src/Web/OIDC/Client/Discovery/Provider.hs:43:49: error:
    • Variable not in scope:
        (<>)
          :: m0 a0
             -> String
             -> aeson-1.4.4.0:Data.Aeson.Types.Internal.Parser JwsAlgJson
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Prelude), ‘<*>’ (imported from Prelude),
        ‘*>’ (imported from Prelude)
   |
43 |         other   -> fail $ "Non-supported alg: " <> show (unpack other)
   |                                                 ^^
Failed to install oidc-client-0.4.0.0
```

Since it is just strings being concatenated, using `++` should fix it.

**Comment by krdlab** [comment]
Thank you for your report.
Sorry, I had forgotten to import `(<>)`.
#31 passed a build using the lts-11.22 resolver.
